### ISSUE TITLE
Software Engineering - Phase 03 - Naming issue

### ISSUE THREAD

**Issue by Taha-Alikhani** [Star-Academy/codestar-documents#26]
Wrong character naming
![image](https://user-images.githubusercontent.com/31014328/180620473-8c34f76f-e370-4896-948c-5ed39a708833.png)

~ : [tilde](//en.wikipedia.org/wiki/Tilde#ASCII_tilde_(U+007E)])
 `  : [back-tick (AKA back-quote )](https://en.wikipedia.org/wiki/Backtick)

**Comment by BijanEisapour** [comment]
ممنون از اینکه issue ثبت کردی

برای دریافت امتیاز، مشکلات نگارشی رو باید خودت حل کنی
یعنی باید PR بزنی 

اما اگه امتیاز نمیخوای، بگو خودمون مشکل رو حل کنیم
