### ISSUE TITLE
پیشنهاد بازی برای یادگرفتن فلکس در قسمت pilot

### ISSUE THREAD

**Issue by AtaReversei** [Star-Academy/codestar-documents#31]
https://mastery.games/flexboxzombies/

**Comment by BijanEisapour** [comment]
بهم ارور میده نمیتونم ثبت‌نام کنم

**Comment by AtaReversei** [comment]
با آی پی ایران نمیشه انگار، با شیلترفکنی چیزی امتحان کردم ثبت نام شد

**Comment by BijanEisapour** [comment]
خییییلی طول میکشه load شه 
ترجیح میدم تو مستندات نذارمش
