### ISSUE TITLE
SQL docs: notes for linux users

### ISSUE THREAD

**Issue by Soltaniant** [Star-Academy/codestar-documents#70]
**postgresql connection:** while creating new connection in Azure Data Studio, you are asked to fill a `password` field. while during installation no password setting was required. the problem was solved by querying on postgresql shown in [this](https://stackoverflow.com/questions/27107557/what-is-the-default-password-for-postgres) link. @abolfazlghalandary himself, provide this link for us. 

**installing postgresql extension on ADS:** unfortunately auto-installing this extension was not possible. it requires to install it from VSIX. which should be externally downloaded from [this](https://sqlopsextensions.blob.core.windows.net/extensions/postgresql/azuredatastudio-postgresql-0.2.7.vsix) link.

**Comment by BijanEisapour** [comment]
به نظر میرسه قبلاً به داک اضافه شده.
